services:
  db:
    image: postgres:15-alpine
    container_name: payme-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: